FROM node:alpine AS dev   

WORKDIR /app

# COPY package.json package-lock.json  ./
COPY .  .

# RUN npm install && npm run build && rm -rf ./node_modules/
RUN npm install && npm i -g @angular/cli

EXPOSE 4200


CMD [ "ng","serve","--host", "0.0.0.0" ]